name: CI/CD for NPM Plugins Hieroglyphs.io

on:
  push:
    branches:
      - master

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Clonage du repo
      uses: actions/checkout@v3

    - name: Configuration Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        registry-url: 'https://registry.npmjs.org/'

    - name: Installation des librairies
      run: npm install

    - name: Authentification à npmjs.com
      run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Test sur les plugins
      run: npm test

    - name: Construction du projet
      run: npm run build

    - name: Publish sur NPM
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: npm publish

    - name: Création de la liste des plugins
      run: |
        echo "Début de la génération de la liste des plugins..."
        echo "Plugin and function list:" > plugin-list.txt
        for file in src/lib/*.js; do
          echo "Traitement du fichier : $file"
          if [ -f "$file" ]; then
            # Extraction des fonctions avec gestion des fichiers sans correspondance
            func_name=$(grep -o 'function [a-zA-Z_][a-zA-Z0-9_]*' "$file" | awk '{print $2}' || true)
            if [ -n "$func_name" ]; then
              echo "$(basename "$file"): $func_name" >> plugin-list.txt
            else
              echo "$(basename "$file"): No function found" >> plugin-list.txt
            fi
          else
            echo "Pas de fichiers .js trouvés dans src/lib/"
          fi
        done
        echo "Contenu de plugin-list.txt :"
        cat plugin-list.txt
      shell: bash

    - name: Sauvegarde de plugin-list.txt
      uses: actions/upload-artifact@v3
      with:
        name: plugin-list
        path: plugin-list.txt
    
    